use uuid::Uuid;

/// Authenticated user identity used by application flows.
#[derive(Debug, Clone)]
pub struct UserAuth {
    /// Stable unique identifier for the user record.
    pub id: Uuid,
    /// Canonical login identifier for the user.
    pub email: String,
    /// Password hash generated by infrastructure-approved hashing strategy.
    pub password_hash: String,
}

/// Session payload persisted in a session store.
#[derive(Debug, Clone)]
pub struct SessionData {
    /// Subject user identifier.
    pub user_id: Uuid,
    /// Email copy used by downstream session consumers.
    pub email: String,
}
