use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Authenticated user identity used by application flows.
#[derive(Debug, Clone)]
pub struct UserAuth {
    /// Stable unique identifier for the user record.
    pub id: Uuid,
    /// Canonical login identifier for the user.
    pub email: String,
    /// Password hash generated by infrastructure-approved hashing strategy.
    pub password_hash: String,
}

/// Standard JWT claims used by the authentication flow.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuthTokenClaims {
    /// Subject user identifier.
    pub sub: String,
    /// User email claim.
    pub email: String,
    /// Issued-at timestamp (unix seconds).
    pub iat: u64,
    /// Expiration timestamp (unix seconds).
    pub exp: u64,
    /// Token unique identifier.
    pub jti: String,
}
